apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
type: Opaque #arbitrary user-defined data
data:
  DB_USER: bW9qdXp5dGtvd25pawo=
  DB_PASSWORD: bW9qZWhhc2xvZjM0ZjM0Mwo=
