apiVersion: v1
kind: Pod
metadata:
  labels:
    chapter: configmaps
  name: podzconfigmapa
spec:
  containers:
    - name: ctr1
      image: busybox
      command: [ "/bin/sh", "-c", "watch -n 10 echo First name: $(FIRSTNAME) last name: $(LASTNAME) company: $(CAR)" ]
      env:
        - name: FIRSTNAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: given
        - name: LASTNAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: family   
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"




# FIRSTNAME=Roman
# LASTNAME=Erotoman
# COMPANY=ING