apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
  labels:
    name: nginx-env
spec:
  containers:
  - name: nginx-env
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    env:
      - name: POD_ENV
        value: "Tak, to nginx"
        