apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d # mount nginx-conf volume to /etc/nginx/conf.d
      readOnly: true
      name: nginx-conf
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: html-conf
    resources:
      limits:
        memory: 150Mi
        cpu: 200m
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx/conf.d/default.conf file
      items:
        - key: nginx.conf
          path: default.conf


- stworz nowy obiekt confimap dodaj do niego index.html i wrzuca tam jakas zawartosc np "edzio pedzio"
- stowrz trzeci obiekt config map w ktorym bedziesz przechowywal swoje CK i to CK ma byc udostepnione w 
  kontenerze w katalogu /home/mojeck.conf
- nie wchodza do kontenera wyswietl czy plik zostal zaimportowany "ls -l /home/"
