apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.17
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 1.5
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi







