apiVersion: v1 
kind: Pod 
metadata: 
  name: double-container
spec: 
  containers: 
  - name: ubuntu 
    image: ubuntu:latest 
    command: [ "sleep", "inf" ] 
  - name: nginx 
    image: nginx 
    ports: 
    - containerPort: 80
