apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
  - name: ubuntu
    image: ubuntu:22.04
    command: [ "sleep", "inf" ]
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: httpd
    image: httpd
    ports:
      - containerPort: 80
