apiVersion: v1
kind: Pod
metadata:
  name: color-app
  labels:
    name: color-app
spec:
  containers:
  - name: color-app
    image: lextsy/color-app
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: "blue"
