apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: worker-app-pod
    spec:
      containers:
      - name: worker-app
        image: lextsy/examplevotingapp_worker
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      
