apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: namespace
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox
    command: ['sh', '-c', 'echo Welcome to edzio pedzio World ! && sleep 3600']