apiVersion: v1
kind: ConfigMap
metadata:
  name: moja-cm
data:
  wlasnyindex.conf: |
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>Nasz htmlllll/title>
      </head>
      <body>
        <p> This is content from Config Map (html.conf)
      </body>
    </html>