apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    env:
      - name: CK
        valueFrom:
          configMapKeyRef:
            name: employee
            key: nameck
      - name: TEAM
        valueFrom:
          configMapKeyRef:
            name: employee
            key: nameteam
      - name: CARD_NUMBER
        valueFrom:
          secretKeyRef:
            name: ing-data
            key: number
      - name: CVV_CODE
        valueFrom:
          secretKeyRef:
            name: ing-data
            key: code
    volumeMounts:
    - mountPath: /users/
      readOnly: true
      name: passwd-conf
  volumes:
  - name: passwd-conf
    configMap:
      name: passwd-conf
      items:
        - key: passwd.conf
          path: passwd.conf



