apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
spec:
  replicas: 3
  selector: 
    matchLabels:
      name: k8s-webapp
  template:
    metadata:
      labels:
        name: k8s-webapp
    spec:
      containers:
      - name: webapp-ctr
        image: nginx:1.20
        ports:
        - containerPort: 80
        resources:
          limits:
           memory: 200Mi
           cpu: 300m
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    name: k8s-webapp