apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-liveness-readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-api-liveness-readiness
  template:
    metadata:
      labels:
        name: web-api-liveness-readiness
    spec:
      containers:
      - name: webapi
        # image: k8smaestro/web-api:1.0
        image: iamassistant.azurecr.io/iamasistantfrontend:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/liveness"
            port: 3000
            # httpHeaders:
            # - name: "Cookie"
            #   value: "session-id=x-readiness-probe"
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/readiness"
            port: 3000
            # httpHeaders:
            # - name: "Cookie"
            #   value: "session-id=x-liveness-probe"
        resources:
          requests:
            cpu: 100m
            memory: 220Mi
          limits:
            cpu: 200m
            memory: 450Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-web-api-liveness-readiness
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    name: web-api-liveness-readiness

