apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: html-conf
  volumes:
  - name: html-conf
    configMap:
      name: html-conf 
      items:
        - key: html.conf
          path: index.html
---

- wlasna configmapa
  - nazwa cm users-home
  - nazwa volumena users-home
  - mountPath /home
  - w /home ma sie znalezc plik z nazwa waszego ck.
    a ten plik ma sie nazywa user.conf
  
