apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
      readOnly: true
      name: html-conf
    resources:
      limits:
        memory: 150Mi
        cpu: 200m
  volumes:
  - name: html-conf
    configMap:
      name: html-conf 
      items:
        - key: html.conf
          path: index.html
