apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: postgres-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: postgres-pod
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: db-data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_HOST_AUTH_METOD
            value: trust
      volumes:
      - name: db-data
        emptyDir: {}
