apiVersion: v1
kind: Pod
metadata:
  name: nginx8080
spec:
  containers:
  - name: nginx8080
    image: nginx
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: 150m
        memory: 220Mi
      limits:
        cpu: 200m
        memory: 450Mi







