apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
    version: 1.0.0
    env: prod
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
  labels:
    name: nginx
    version: 2.0.0
    env: dev
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80