apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: "new app version"
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80